<?php
    /**
     * @name:       Samp Front
     * @version:    0.5.0
     * @author:     EOussama (eoussama.github.io)
     * @license     MIT
     * @source:     github.com/EOussama/samp-front
     */

    /**
     * Returns the appropriate icon name.
     */
    function get_icon($label) {
        return (in_array($label, array(
                "accusoft",
                "adn",
                "adversal",
                "affiliatetheme",
                "algolia",
                "amazon",
                "amilia",
                "android",
                "angellist",
                "angrycreative",
                "angular",
                "app store",
                "apper",
                "apple",
                "apple pay",
                "asymmetrik",
                "audible",
                "autoprefixer",
                "avianex",
                "aviato",
                "aws",
                "bandcamp",
                "behance",
                "bimobject",
                "bitbucket",
                "bitcoin",
                "bity",
                "black tie",
                "blackberry",
                "blogger",
                "bluetooth",
                "btc",
                "buromobelexperte",
                "buysellads",
                "on pay",
                "centercode",
                "chrome",
                "cloudscale",
                "cloudsmith",
                "cloudversify",
                "codepen",
                "codiepie",
                "connectdevelop",
                "contao",
                "cpanel",
                "creative commons",
                "cuttlefish",
                "dashcube",
                "delicious",
                "deploydog",
                "deskpro",
                "deviantart",
                "digg",
                "digital ocean",
                "discord",
                "discourse",
                "dochub",
                "docker",
                "draft2digital",
                "dribbble",
                "dropbox",
                "drupal",
                "dyalog",
                "earlybirds",
                "edge",
                "elementor",
                "ember",
                "empire",
                "envira",
                "erlang",
                "ethereum",
                "etsy",
                "expeditedssl",
                "facebook",
                "firefox",
                "first order",
                "firstdraft",
                "flickr",
                "flipboard",
                "fly",
                "forumbee",
                "foursquare",
                "free code camp",
                "freebsd",
                "get pocket",
                "github",
                "gitkraken",
                "gitlab",
                "gitter",
                "glide",
                "gofore",
                "goodreads",
                "google drive",
                "google play",
                "google plus",
                "google wallet",
                "gratipay",
                "grav",
                "gripfire",
                "hacker news",
                "hips",
                "hire a helper",
                "hooli",
                "hotjar",
                "houzz",
                "html5",
                "hubspot",
                "imdb",
                "instagram",
                "ioxhost",
                "itunes",
                "jenkins",
                "joget",
                "joomla",
                "jsfiddle",
                "keycdn",
                "kickstarter",
                "korvue",
                "laravel",
                "lastfm",
                "leanpub",
                "less",
                "linechat",
                "linkedin",
                "linode",
                "linux",
                "lyft",
                "magento",
                "maxcdn",
                "medapps",
                "medium",
                "medrt",
                "meetup",
                "microsoft",
                "mix",
                "mixcloud",
                "mizuni",
                "modx",
                "monero",
                "napster",
                "npm",
                "ns8",
                "nutritionix",
                "odnoklassniki",
                "opencart",
                "openid",
                "opera",
                "optin monster",
                "osi",
                "page4",
                "pagelines",
                "palfed",
                "patreon",
                "paypal",
                "periscope",
                "phabricator",
                "php",
                "pied piper",
                "pinterest",
                "playstation",
                "product hunt",
                "pushed",
                "python",
                "qq",
                "quinscape",
                "quora",
                "ravelry",
                "rebel",
                "redriver",
                "reddit",
                "rendact",
                "renren",
                "replyd",
                "resolving",
                "rocketchat",
                "rockrms",
                "safari",
                "sass",
                "schlix",
                "scribd",
                "searchengin",
                "sellcast",
                "sellsy",
                "servicestack",
                "shirtsinbulk",
                "simplybuilt",
                "sistrix",
                "skyatlas",
                "skype",
                "slack",
                "slideshare",
                "snapchat",
                "soundcloud",
                "speakap",
                "spotify",
                "stack exchange",
                "stack overflow",
                "staylinked",
                "steam",
                "sticker mule",
                "strava",
                "stripe",
                "studiovinari",
                "stumbleupon",
                "stumbleupon circle",
                "superpowers",
                "supple",
                "telegram",
                "telegram plane",
                "tencent weibo",
                "themeisle",
                "trello",
                "tripadvisor",
                "tumblr",
                "twitch",
                "twitter",
                "typo3",
                "uber",
                "uikit",
                "uniregistry",
                "untappd",
                "usb",
                "ussunnah",
                "vaadin",
                "viacoin",
                "viadeo",
                "viber",
                "vimeo",
                "vine",
                "vk",
                "vnv",
                "wechat",
                "weibo",
                "weixin",
                "whatsapp",
                "whmcs",
                "wikipedia",
                "windows",
                "wordpress",
                "wordpress simple",
                "wpbeginner",
                "wpexplorer",
                "wpforms",
                "xbox",
                "xing",
                "y combinator",
                "yahoo",
                "yandex",
                "yelp",
                "yoast",
                "youtube"
            )) ? $label : "external alternate");
    }